### ISSUE TITLE
MongolEditText 如何监听回车按键 

### ISSUE THREAD

**Issue by XinleiChenJohn** [suragch/mongol-library#4]
我在用MongolEditText做搜索功框，但是我没办法监听到回车按键，我们的需求是回车就可以搜索，
如果需要改源码，我应该在哪里改

**Comment by suragch** [comment]
应该可以用`mongolEditText.addTextChangedListener(TextWatcher watcher)`，然后监听回车。

参考以下的有关内容：
- https://stackoverflow.com/questions/37910880/edittext-on-word-wrap-new-line-listener
- https://stackoverflow.com/questions/21976590/detect-newline-in-edittext

**Comment by XinleiChenJohn** [comment]
`mongolEditText.addTextChangedListener(TextWatcher watcher)`并不能监听到回车输入，按回车的时候
没有走`onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int)`监听方法
还有一个问题，蒙文是不是从右往左的？

**Comment by XinleiChenJohn** [comment]
谢谢大佬
```
addTextChangedListener(object :TextWatcher{
            override fun afterTextChanged(s: Editable?) {

            }

            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {
            }

            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
                if (s?.contains("\n") == true) {
                         //do something
                }
            }
        })
```
