### ISSUE TITLE
使用MongolEditText的时候回车如何变成搜索

### ISSUE THREAD

**Issue by XinleiChenJohn** [suragch/mongol-library#5]
就比如这样
![image](https://user-images.githubusercontent.com/31652110/61445162-6c094b80-a97f-11e9-8734-59433c1b1a67.png)

**Comment by suragch** [comment]
哦 明白了 你们需要这种功能是吗？https://stackoverflow.com/a/3205405/3681880

我得研究EditText是怎么实施的。

Public description:

- `MongolEditText` does not currently have a `setOnEditorActionListener` and cannot handle `EditorInfo.IME_ACTION_SEARCH`.
- Need to add an XML option to set the `EditorInfo` and add the listener to `MongolEditText`. Study how the EditText source code does it.

**Comment by XinleiChenJohn** [comment]
谢谢，非常感谢

**Comment by suragch** [comment]
@XinleiChenJohn 试一试 我加了imeOptions和inputType

    <net.studymongolian.mongollibrary.MongolEditText
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        app:inputType="number"
        app:imeOptions="actionSearch" />

监听方法：

    MongolEditText metSearch = findViewById(R.id.met_search);
    metSearch.setOnEditorActionListener(new MongolEditText.OnEditorActionListener() {
        @Override
        public boolean onEditorAction(MongolEditText v, int actionId, KeyEvent event) {
            // ...
            return true;
        }
    });

**Comment by XinleiChenJohn** [comment]
好了，不能像使用EditText那样常规去拦截，我是这么写的
```kotlin
 searchMET.setOnEditorActionListener { _, actionId, _ ->
            if (actionId == 3/*KeyEvent.KEYCODE_ENTER&&event.action==KeyEvent.ACTION_DOWN 这个不好使只好拦截 == 3*/){
                keyWord = if (!searchMET.text.isNullOrEmpty()){
                    searchMET.text.toString()
                }else{
                    ""
                }
                KeyboardUtils.hideSoftInput(searchMET)
                searchMET.setText(searchMET.text.toString().trim())
                allAccRefresh.autoRefresh()
            }
            true
        }
```

**Comment by suragch** [comment]
@XinleiChenJohn 这样也可以：

```
if (actionId == EditorInfo.IME_ACTION_SEARCH) {
  // ...
}
```
